model = "gpt-5.4"
model_reasoning_effort = "xhigh"
personality = "pragmatic"

[features]
multi_agent = true

[notice]
hide_full_access_warning = true

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"
"gpt-5.2" = "gpt-5.3-codex"
"gpt-5.3-codex" = "gpt-5.4"
